### ISSUE TITLE
API should return proper error message on passing wrong url parameters

### ISSUE THREAD

**Issue by jasleenChauhan** [nearform/autocannon-ui#10]
Steps to re-produce. 

1. Go to Postman and create the below POST request:
URL: http://localhost:3000/api/execute
Body:
```
{
    "url": "dgjhsdhgj",
    "connections": 10,
    "method": "POST",
    "duration": "10",
    "pipelining": 1
}
```

**Expected Behaviour:** API should return proper error message on passing wrong url parameters.

**Expected response:**

**HTTP Status Code:** 400

Error code:  Bad Request Exception

```
Response Example:
{
	"errorCode": "Bad Request"
	"message": "Invalid value of url"
}
```

**Observed Behaviour:** 

1. API returns 200 response

**Comment by simoneb** [comment]
This is now fixed in the latest version on master.
