### ISSUE TITLE
Publish docker image with release

### ISSUE THREAD

**Issue by nabeelbukhari** [nearform/autocannon-ui#1086]
**npx autocannon-ui** allows running autocannon-ui from cli but requires fetching long list of packages everytime it is setup on a new machine. 

We want to setup running autocannon-ui from container by publishing a new image with release so that it can be setup and run quickly.

**Comment by nabeelbukhari** [comment]
@simoneb Can you add some thoughts how would you like it to be done?

**Comment by simoneb** [comment]
I simply don't think the docker setup should live in this repo

**Comment by nabeelbukhari** [comment]
Why cant we make it part of github actions?

**Comment by simoneb** [comment]
Because it should live in user space. Running in docker, or anywhere else, is not part of the responsibilities of a npm package publisher, generally speaking

**Comment by nabeelbukhari** [comment]
@simoneb 

I think we got confused now, I have closed the PR and discussion of running from npm command.

Right now, I am asking about publishing a docker image with each new release so that it can be easily run in container.

I also updated the title of issue.

**Comment by simoneb** [comment]
Again this is not responsibility of this repository. This repository contains the package, if anybody wants to create a docker image they're free to do so, but it's outside of the scope of this project.
