### ISSUE TITLE
API not validating when 'method' parameter is missing in the request

### ISSUE THREAD

**Issue by jasleenChauhan** [nearform/autocannon-ui#11]
**Steps to re-produce**

Go to Postman and create the below POST request:
URL: http://localhost:3000/api/execute
Body:
{
    "url": "https://www.bbc.co.uk/news",
    "connections": 10,
    "duration": "10",
    "pipelining": 1
}

Expected Behaviour: API should validate that method parameter is missing in the request. 

Expected response:

HTTP Status Code: 400

Error code: Bad Request Exception

Response Example:

{
    "errorCode": "Bad Request"
    "message": "Method parameter is missing"
}

Observed Behaviour: Received 200 OK status with below response:

result: {
    "url": "https://www.bbc.co.uk/news",
    "connections": 10,
    "pipelining": 1,
    "duration": 11.03,
    "start": "2021-05-14T14:19:25.973Z",
    "finish": "2021-05-14T14:19:37.002Z",
    "errors": 0,
    "timeouts": 0,
    "mismatches": 0,
    "non2xx": 0,
    "resets": 0,
    "1xx": 0,
    "2xx": 309,
    "3xx": 0,
    "4xx": 0,
    "5xx": 0,
    "statusCodeStats": {
        "200": {
            "count": 309
        }
    },
```

**Comment by simoneb** [comment]
As discussed, all options except url are optional and if not provided they have default values.
