### ISSUE TITLE
Add URL or Title to the response card

### ISSUE THREAD

**Issue by AlessandroSantarini** [nearform/autocannon-ui#58]
Is actually impossible to distinguish between a lot of requests or even different URL. 

The Title (when and if available) or the UR Should be shown near the date.

**Comment by ramonmulia** [comment]
@simoneb is this issue still open?

**Comment by ramonmulia** [comment]
nvm, I see now it is linked with another issue.

**Comment by tiagoheliob** [comment]
@ramonmulia I'll take if you don't mind

**Comment by simoneb** [comment]
@ramonmulia @tiagoheliob what we discussed earlier is that Ramon would work on all of 3 issues in this repo, but I see he has not assigned them yet. Please organize this between the two of you, the only thing I would like is that the same person works on all of them

**Comment by tiagoheliob** [comment]
@simoneb I only see your message only now, but I've coordinated with @ramonmulia already.
