### ISSUE TITLE
Use npx autocannon-ui without the need to running additional commands

### ISSUE THREAD

**Issue by lasmil** [nearform/autocannon-ui#716]
Simplify use of this package:

1) make it possible to run it in this way, which should open a web browser windows on a random port. Note that this may require changing one of the package names
```
npx autocannon-ui
```

2) highlight in the doc that this is the recommended way to run it. iow, this should come as the first thing we mention in the docs

In short, when being on a machine which does not have anything autocannon related, enable running autocannon by running only npx autocannon-ui

**Comment by simoneb** [comment]
It would also be good if we found a way to only publish a single package to npm, right now we're publishing 3. In practice we only need the entry point package to be published: autocannon-ui (what is now autocannon-web). If we found a way to make this repo contain one single package, we could then also start using optic to release it (optic doesn't support monorepos). It would be a good thing to start doing some research and experimentation around this: a repo containing multiple codebases, but publishing only the entry point
